# Generated by Django 6.0.5 on 2026-06-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
            ],
        ),
    ]
